#include <cuda.h>

namespace gpu {

enum ValueType {
	VAL_INVALID = 0,
	VAL_NULL,

	VAL_TINYINT,
    VAL_SMALLINT,
    VAL_INTEGER,
    VAL_BIGINT,
    VAL_DOUBLE,
    VAL_VARCHAR,
    VAL_TIMESTAMP,
    VAL_DECIMAL,
    VAL_BOOLEAN,
    VAL_ADDRESS,
    VAL_VARBINARY,
    VAL_POINT,
    VAL_GEOGRAPHY,
    VAL_ARRAY       = -99,
};

enum ExpressionType {
	EXP_INVALID = 0,
	EXP_OP_EQUAL,
	EXP_OP_NOT_EQUAL,
	EXP_OP_AND,
	EXP_OP_OR,
	EXP_OP_NEGATE,
	EXP_OP_GREATER_THAN,
	EXP_OP_LESS_THAN,
	EXP_OP_GREATER_THAN_OR_EQUAL,
	EXP_OP_LESS_THAN_OR_EQUAL,
	EXP_OP_ADD,
	EXP_OP_SUBTRACT,
	EXP_OP_MULTIPLY,
	EXP_OP_DIVIDE,

    EXP_VALUE_CONSTANT,
    EXP_VALUE_PARAMETER,
    EXP_VALUE_TUPLE,
    EXP_VALUE_TUPLE_ADDRESS,
    EXP_VALUE_NULL,
    EXP_VALUE_VECTOR,
    EXP_VALUE_SCALAR,

    EXP_AGGREGATE_COUNT,
    EXP_AGGREGATE_COUNT_STAR,
    EXP_AGGREGATE_SUM,
    EXP_AGGREGATE_MIN,
    EXP_AGGREGATE_MAX,
    EXP_AGGREGATE_AVG,
    EXP_AGGREGATE_APPROX_COUNT_DISTINCT,
    EXP_AGGREGATE_VALS_TO_HYPERLOGLOG,
    EXP_AGGREGATE_HYPERLOGLOGS_TO_CARD,

    EXP_FUNCTION,

};

enum IndexLookupType {
   INDEX_LOOKUP_TYPE_INVALID = 0,
   INDEX_LOOKUP_TYPE_EQ      = 1,
   INDEX_LOOKUP_TYPE_GT      = 2,
   INDEX_LOOKUP_TYPE_GTE     = 3,
   INDEX_LOOKUP_TYPE_LT      = 4,
   INDEX_LOOKUP_TYPE_LTE     = 5,
   INDEX_LOOKUP_TYPE_GEO_CONTAINS = 6,
};
}
